apiVersion: batch/v1
kind: CronJob
metadata:
 name: hello-cronjob
 namespace: mateapp
spec:
 schedule: "*/4 * * * *"
 concurrencyPolicy: Allow
 startingDeadlineSeconds: 100
 successfulJobsHistoryLimit: 10
 failedJobsHistoryLimit: 5
 jobTemplate:
   spec:
     template:
       spec:
         containers:
           - name: todoapp
             image: ikulyk404/busyboxplus:curl
             command:
               - /bin/sh
               - -c
               - curl http://172.18.0.4:30008/api/health
         restartPolicy: OnFailure
